# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: product_service.proto for package 'rpc'

require 'grpc'
require_relative 'product_service_pb'

module Rpc
  module ProductService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.ProductService'

      rpc :GetProducts, ::Rpc::ProductsRequest, ::Rpc::ProductsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
